platform:ios, '8.0'
target 'SwiftTest' do
pod 'AFNetworking', '~>3.1.0'
pod 'FMDB', '~>2.6.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'IQKeyboardManagerSwift', '>= 4.0.7'
pod 'Kingfisher', '~> 4.2.0'
pod 'Alamofire', '>=4.2.0'
pod 'SwiftyJSON', '>= 3.1.3'
pod 'SnapKit', '~> 4.0.0'
#pod 'AsyncSwift'
pod 'SVProgressHUD'
#pod 'AlamofireNetworkActivityIndicator', '~> 2.1.0'
#pod 'AlamofireImage', '~> 3.2.0'
#pod 'HandyJSON', '~> 1.4.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'Meiqia', '~> 3.4.5'
pod 'HyphenateLite', '~> 3.3.4.1'
pod 'Masonry', '~> 1.0.2'
pod ‘UMengUShare/Social/WeChat'
pod 'MLeaksFinder'
pod 'SQLite.swift', '~> 0.11.4'
pod 'YYModel', '~> 1.0.4'
pod 'YYText', '~> 1.0.7'
pod 'GTSDK'

use_frameworks!
end

